liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumbnail_small:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        thumbnail_medium:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        thumbnail_large:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: inset }
